name: Actualizar total de cartas FC Mobile

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Crear archivo total.json desde Renderz
        run: |
          npm install axios
          node -e "
          const axios = require('axios');
          async function run() {
            try {
              const res = await axios.get('https://renderz.app/api/players?grl=all');
              const jugadores = res.data.players;
              const seleccionados = jugadores.filter(j => j.ovr >= 104 && j.ovr <= 109);
              const total = seleccionados.reduce((s, j) => s + (j.value || 0), 0);
              const fs = require('fs');
              fs.writeFileSync('total.json', JSON.stringify({ total, actualizado: new Date().toISOString() }, null, 2));
            } catch (err) {
              console.error('ERROR AL CONSULTAR RENDERZ:', err.response?.data || err.message);
              process.exit(1);
            }
          }
          run();
          "

      - name: Subir archivo total.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull origin principal || true
          git add total.json
          git commit -m "Actualizar total.json automáticamente" || echo "Sin cambios"
          git push origin principal
