name: Actualizar total de cartas FC Mobile

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install axios

      - name: Obtener datos y generar total.json
        run: |
          node -e "
          const axios = require('axios');
          async function run() {
            const res = await axios.get('https://renderz.app/api/players');
            const jugadores = res.data.players;
            const seleccionados = jugadores.filter(j => j.ovr >= 104 && j.ovr <= 109);
            const total = seleccionados.reduce((s, j) => s + (j.value || 0), 0);
            const fs = require('fs');
            fs.writeFileSync('total.json', JSON.stringify({ total, timestamp: new Date().toISOString() }, null, 2));
          }
          run();
          "

      - name: Subir total.json al repositorio
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull origin principal || true
          git add total.json
          git commit -m "Actualizar total.json automáticamente" || echo "Sin cambios"
          git push origin principal